import Head from "next/head";
import NavbarIntranet from "../intranet/navbarIntranet";
export default function LayoutIntranet({ children, admin }) {
  return (
    <>
      <div className="">
        <Head>
          <title>Broccoli Intranet</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavbarIntranet admin={admin} />
        <section>
          <div className="">{children}</div>
        </section>
      </div>
    </>
  );
}
