import Head from "next/head";
import Footer from "../footer";
import NavbarAdmin from "../intranet/navbarAdmin";
import NavBar from "../navbar/navbar";
export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Broccoli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <section>
        <div className="">{children}</div>
      </section>

      <Footer />
    </>
  );
}
