


import Head from 'next/head'
import Image from 'next/image';
import { userAgentFromString } from 'next/server';
import Footer from '../footer';
import NavbarIntranet from '../intranet/navbar';
export default function LayoutIntranet({ children, user }) {
    return (
        <>
        <Head>
            <title>Broccoli Intranet</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
      

        <NavbarIntranet user={user}/>
        <section>
            
            <div className="">
            {children}
            </div>
        </section>
            
    </>


    );

}