import styles from './layout.module.css'
import NavBar from './navbar';

import Head from 'next/head'
import Footer from './footer';
export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <div >

                {children}
            </div>
            <Footer />
        </>

    );

}