import styles from './layout.module.css'
import NavBar from './navbar';

import Head from 'next/head'
import Footer from './footer';
import Image from 'next/image';
export default function LayoutHome({children}) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />    
            </Head>
            <NavBar  className={styles.navbar} />
            
            <div className={styles.container}> 
            
                {children} 
            </div>
            <Footer />
        </>
        
    );
    
}