import Head from 'next/head'
import {authenticate} from "./authenticate";
import formStyles from "../form.module.css"
import styles from "../../../styles/Home.module.css";

export async function getServerSideProps(context) {
    let authentication = await authenticate(context)
    if (authentication !== undefined) return authentication
    return {props: {}}
}

export default function Home() {
    return (
            <div className={styles.container}>
                <Head>
                    <title>Admin</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/public/favicon.ico" />
                </Head>
                <main>
                    <div>
                        <form className={formStyles.form} action="../../api/createuser" method="POST">
                            <input type="text" name="username" placeholder="Användarnamn"/>
                            <input type="text" name="password" placeholder="Lösenord"/>
                            <input type="text" name="firstname" placeholder="Förnamn"/>
                            <input type="text" name="lastname" placeholder="Efternamn"/>
                            <input type="text" name="email" placeholder="Email"/>
                            <input type="text" name="address" placeholder="Address"/>
                            <input type="text" name="privatenumber" placeholder="Privattelefon"/>
                            <input type="text" name="worknumber" placeholder="Arbetstelefon"/>
                            <input type="text" name="company" placeholder="Bolag"/>
                            <div>
                                <label> Administratör</label>
                                <input type="checkbox" name="admin" value="true"/>
                            </div>

                            <button type="submit">Lägg till anställd</button>
                        </form>
                    </div>
                </main>
            </div>

    )
}
