import Head from 'next/head'
//import * as Database from '../scripts'

export async function getStaticProps() {
    return {
        props: {}
    }
}

export default function Home() {
    return (
        <div>
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <main>
                <div>
                    <form className='form' action="../../api/createuser" method="POST">
                        <input type="text" name="username" placeholder="Användarnamn"/>
                        <input type="text" name="password" placeholder="Lösenord"/>
                        <input type="text" name="firstname" placeholder="Förnamn"/>
                        <input type="text" name="lastname" placeholder="Efternamn"/>
                        <input type="text" name="address" placeholder="Address"/>
                        <input type="text" name="privatenumber" placeholder="Privattelefon"/>
                        <input type="text" name="worknumber" placeholder="Arbetstelefon"/>
                        <input type="text" name="company" placeholder="Bolag"/>
                        <div>
                            <label> Administratör</label>
                            <input type="checkbox" name="admin" value="true"/>
                        </div>

                        <button type="submit">Lägg till anställd</button>
                    </form>
                </div>
            </main>
        </div>
    )
}
