import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
//import * as Database from '../scripts'

export async function getStaticProps() {
    return {
        props: {}
    }
}

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <h1>
                        Welcome to admin
                    </h1>
                </div>

            </main>
        </div>
    )
}
