import Head from 'next/head'
import styles from '../../../styles/Home.module.css'


export async function getServerSideProps() {
    return {
        props: {firstname: name}
    }
}

export default function Home({firstname}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <h1>
                        Welcome to {firstname}
                    </h1>
                </div>

            </main>
        </div>
    )
}
