import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import * as Database from "../../../Database";

export async function getStaticProps() {
    //const firstname = await Database.getFirstname('633d5c12e0bf4ed28b2c3428')
    let firstname = "Broccoli"
    return {
        props: {}
    }
}

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <h1>
                        Welcome
                    </h1>
                </div>

            </main>
        </div>
    )
}
