import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import * as Database from "../../../Database";
import {authenticate} from "./authenticate";

export async function getServerSideProps(context) {
    let authentication = await authenticate(context)
    if (authentication !== undefined) return authentication

    let user = await Database.getAllUsers()
    return {
        props: {user: user}
    }
}

export default function Home({user}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Anställda</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div>
                    <table>
                        <thead>
                            <tr>
                                <th>Användarnamn</th>
                                <th>Förnamn</th>
                                <th>Efternamn</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Privatnummer</th>
                                <th>Arbetsnummer</th>
                                <th>Bolag</th>
                                <th>Admin</th>
                            </tr>
                        </thead>
                        <tbody>
                        {user.map((u,i) =>
                            <tr key={i}>
                                <td>{u.username}</td>
                                <td>{u.firstname}</td>
                                <td>{u.lastname}</td>
                                <td>{u.email}</td>
                                <td>{u.address}</td>
                                <td>{u.privatenumber}</td>
                                <td>{u.worknumber}</td>
                                <td>{u.company}</td>
                                <td>{String(u.admin)}</td>
                            </tr>
                        )}
                        </tbody>
                    </table>
                    <a href={"./createuser"}> Ny anställd</a>
                </div>

            </main>
        </div>
    )
}
