import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import * as Database from "../../../Database";
import {authenticate} from "./authenticate";
import popupStyles from "../popup.module.css"
import formStyles from "../form.module.css";

export async function getServerSideProps(context) {
    let authentication = await authenticate(context)
    if (authentication !== undefined) return authentication

    let user = await Database.getAllUsers()
    return {
        props: {user: user}
    }
}

export default function Home({user}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Anställda</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div id="modifyuser" className={`${popupStyles.window} ${popupStyles.hide}`}>
                    <form className={formStyles.form} action="../../api/modify" method="POST">
                        <input type="text" name="username" placeholder="Användarnamn"/>
                        <input type="text" name="password" placeholder="Lösenord"/>
                        <input type="text" name="firstname" placeholder="Förnamn"/>
                        <input type="text" name="lastname" placeholder="Efternamn"/>
                        <input type="text" name="email" placeholder="Email"/>
                        <input type="text" name="address" placeholder="Address"/>
                        <input type="text" name="privatenumber" placeholder="Privattelefon"/>
                        <input type="text" name="worknumber" placeholder="Arbetstelefon"/>
                        <input type="text" name="company" placeholder="Bolag"/>
                        <div>
                            <label> Administratör</label>
                            <input type="checkbox" name="admin" value="true"/>
                        </div>

                        <button type="submit">Ändra anställd</button>
                    </form>
                </div>
                <div id="popup" className={`${popupStyles.popUp} ${popupStyles.hide}`} onClick={function() {
                    document.getElementById("popup").classList.add(popupStyles.hide)
                    document.getElementById("createuser").classList.add(popupStyles.hide)
                    document.getElementById("modifyuser").classList.add(popupStyles.hide)
                }}>
                </div>
                <div id="createuser" className={`${popupStyles.window} ${popupStyles.hide}`}>
                    <form className={formStyles.form} action="../../api/createuser" method="POST">
                        <input type="text" name="username" placeholder="Användarnamn"/>
                        <input type="text" name="password" placeholder="Lösenord"/>
                        <input type="text" name="firstname" placeholder="Förnamn"/>
                        <input type="text" name="lastname" placeholder="Efternamn"/>
                        <input type="text" name="email" placeholder="Email"/>
                        <input type="text" name="address" placeholder="Address"/>
                        <input type="text" name="privatenumber" placeholder="Privattelefon"/>
                        <input type="text" name="worknumber" placeholder="Arbetstelefon"/>
                        <input type="text" name="company" placeholder="Bolag"/>
                        <div>
                            <label> Administratör</label>
                            <input type="checkbox" name="admin" value="true"/>
                        </div>

                        <button type="submit">Lägg till anställd</button>
                    </form>
                </div>


                <div>

                    <table>
                        <thead>
                            <tr>
                                <th>Användarnamn</th>
                                <th>Förnamn</th>
                                <th>Efternamn</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Privatnummer</th>
                                <th>Arbetsnummer</th>
                                <th>Bolag</th>
                                <th>Admin</th>
                            </tr>
                        </thead>
                        <tbody>
                        {user.map((u,i) =>
                            <tr key={i}>
                                <td>{u.username}</td>
                                <td>{u.firstname}</td>
                                <td>{u.lastname}</td>
                                <td>{u.email}</td>
                                <td>{u.address}</td>
                                <td>{u.privatenumber}</td>
                                <td>{u.worknumber}</td>
                                <td>{u.company}</td>
                                <td>{String(u.admin)}</td>
                            </tr>
                        )}
                        </tbody>
                    </table>

                    <button onClick={function() {
                        document.getElementById("popup").classList.remove(popupStyles.hide)
                        document.getElementById("createuser").classList.remove(popupStyles.hide)
                    }}> Ny anställd</button>
                </div>

            </main>
        </div>
    )
}
