import FullCalendar from "@fullcalendar/react";
import interactionPlugin from "@fullcalendar/interaction";
import dayGridPlugin from '@fullcalendar/daygrid';
import styles from "./calendar.modules.css";
import Head from "next/head";

const Calendar = () => {
    return (
        <FullCalendar
            plugins={[dayGridPlugin, interactionPlugin]}
            editable
            selectable
            select={function (e) {
                console.log(e)
            }}
            eventClick={function (e) {
                console.log(e.event.id)
            }}
            eventDrop={function(e) {
                console.log(e)
            }}
            events={[
                {id: '1', title: 'event1', start: '2022-10-13', end:'2022-10-16'}
            ]}
        />
    );
};

export default function Home() {
    return (
        <div>
            <div className={styles.popUp}>
                <div id='createEvent'>

                </div>
                <div id='checkEvent'>

                </div>
                <div id='modifyEvent'>

                </div>
            </div>
            <Head>
                <title>Admin</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div>
                    {Calendar()}
                </div>

            </main>
        </div>
    )
}
