import Head from 'next/head'
import * as Database from "../../Database";
import styles from "../../styles/Home.module.css";
import formStyles from "./form.module.css"

export async function getServerSideProps(context) {
    let cookies = context.req.cookies['userid']
    let user = await Database.getUserinfo(cookies)
    if (user === undefined || user === null) {
        return {
            redirect: {
                permanent: false,
                destination: "/intranet",
            },
            props:{},
        };
    }
    else {
        return {
            props: {
                user: user,
            }
        }
    }
}

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Intranet</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>

            <main>
                <div>
                    <h1>
                        Please log in
                    </h1>
                    <form className={formStyles.form} action="../../api/send_email" method="POST">
                        <input type="text" name="content" placeholder="mail"/>
                        <button type="submit">Send email</button>
                    </form>
                </div>
            </main>
        </div>
    )
}
