import Head from 'next/head'
import Nyheter from '../../components/intranet/newsItem';
import LayoutIntranet from '../../components/layout/layoutIntranet';
import * as Database from "../../Database";
import styles from "../../styles/Home.module.css";
import formStyles from "./form.module.css"

export async function getServerSideProps(context) {
    let cookies = context.req.cookies['userid']

    let user = await Database.getUserinfo(cookies)
    let groups = await Database.getAllLunchGroups()
    let lunchgroups = []
    groups.slice(1).map((data) => {
        let people = []
        data.users.map((usr) => {
            let fullName = usr.firstname + usr.lastname
            people.push(fullName)
        })
        let object = { title: data.title, people: people }
        lunchgroups.push(object)
    })
    return {

        props: {
            user: user === undefined ? null : user,
            lunchgroups: lunchgroups
        }
    }
}

export default function Home({ user, lunchgroups }) {
    if (user === null) {
        return (
            <div className="layout align-center w-1/3 h-screen flex flex-col justify-center">
                <Head>
                    <title>Intranet</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/public/favicon.ico" />
                </Head>

                <main>
                    <div className='layout py-12 flex flex-1 justify-center flex-col items-center border-2 border-purple-1 shadow-lg rounded-md md:rounded-3xl ' >
                        <h1>
                            Sign in
                        </h1>
                        <form className="flex flex-col flex-1 py-12" action="../../api/login" method="POST">


                            <input className='p-2 m-2 border border-zinc-200 appearance-none  rounded-md  shadow leading-tight focus:outline focus:outline-offset-1 focus:outline-2 focus:outline-purple-1 autofill:bg-theme-green autofill:focus:bg-black' type="text" name="username" placeholder="Användarnamn" />

                            <input className='p-2 m-2 border border-zinc-200 appearance-none  rounded-md  shadow leading-tight focus:outline focus:outline-offset-1 focus:outline-2 focus:outline-purple-1 autofill:bg-theme-green autofill:focus:bg-black' type="password" name="password" placeholder="Lösenord" />
                            <button className="shadow bg-purple-3 hover:bg-purple-2 focus:shadow-outline focus:outline-none text-white font-semibold p-2 m-2  rounded" type="submit">Log in</button>
                        </form>
                    </div>

                </main>
            </div>
        )
    } else {
        const lunchfuldata = [
            {
                title: "Arendal",
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },
            {
                title: "Lundby",
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },
            {
                title: "Arendal", 
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },
            {
                title: "Arendal", 
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },
            {
                title: "Arendal", 
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },
            {
                title: "Arendal", 
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },
            {
                title: "Arendal", 
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            },{
                title: "Arendal", 
                people: ["Anna", "Mathilda", "Stefan", "Johannes", "Kalle"]
            }
        ]
        return (

            <LayoutIntranet>
                <main className=''>

                    <div className='layout py-12  flex flex-col items-center'>

                        <h1>
                            Welcome {user.firstname}
                        </h1>

                        <section>
                            <div className='flex flex-1 flex-col md:flex-row justify-center p-5'>
                                <Nyheter />

                                <div className='flex flex-col bg-purple-1 p-2 m-2 '>
                                    <h3>Lunchgrupper</h3>
                                    <div className='flex flex-1 flex-wrap flex-row  bg-red-300'>
                                        {lunchfuldata.map((pp) => {
                                            return (
                                                <div className='flex flex-col p-2  md:p-5'>
                                                    <h5 className='font-semibold'>{pp.title}</h5>
                                                    {pp.people.map((i) => {
                                                        return (

                                                            <p>{i}</p>
                                                        )
                                                    })}

                                                </div>
                                            )
                                        })}
                                    </div>
                                </div>
                            </div>
                        </section>

                    </div>
                </main>

            </LayoutIntranet>

        )
    }
}
